version: 2
updates:
  - package-ecosystem: maven
    directory: "/java"
    schedule:
      interval: weekly
      day: monday
      timezone: Europe/London
    open-pull-requests-limit: 10
    rebase-strategy: disabled
